<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <OpenApiGenerateDocuments>true</OpenApiGenerateDocuments>
    <OpenApiDocumentsDirectory>$(MSBuildProjectDirectory)/../../../src/web/openapi</OpenApiDocumentsDirectory>
    <OpenApiGenerateDocumentsOptions>--file-name running-performance --openapi-version OpenApi3_1</OpenApiGenerateDocumentsOptions>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.Extensions.ApiDescription.Server">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
    <ProjectReference Include="../RunningPerformance.Application/RunningPerformance.Application.csproj" />
    <ProjectReference Include="../RunningPerformance.Infrastructure/RunningPerformance.Infrastructure.csproj" />
  </ItemGroup>
</Project>
