<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="../RunningPerformance.Application/RunningPerformance.Application.csproj" />
    <ProjectReference Include="../RunningPerformance.Infrastructure/RunningPerformance.Infrastructure.csproj" />
  </ItemGroup>
</Project>
