namespace RunningPerformance.Application.Ingestion;

public static class NormalizedActivityCsvContract
{
    public const string SchemaVersion = "activities-normalized-v1";

    public static readonly string[] Headers =
    [
        "source_row_number",
        "provisional_activity_key",
        "garmin_activity_id",
        "activity_type",
        "activity_type_source",
        "activity_category",
        "started_at_local",
        "favorite",
        "title",
        "distance_value",
        "distance_unit",
        "calories_kcal",
        "duration_seconds",
        "average_heart_rate_bpm",
        "maximum_heart_rate_bpm",
        "aerobic_training_effect",
        "average_cadence",
        "maximum_cadence",
        "cadence_unit",
        "average_pace_seconds",
        "maximum_pace_seconds",
        "pace_basis",
        "average_speed_kph",
        "maximum_speed_kph",
        "total_ascent_m",
        "total_descent_m",
        "average_stride_length_m",
        "average_vertical_ratio_percent",
        "average_vertical_oscillation_cm",
        "average_ground_contact_time_ms",
        "ground_contact_balance_source",
        "ground_contact_balance_left_percent",
        "ground_contact_balance_right_percent",
        "grade_adjusted_pace_seconds_per_km",
        "normalized_power_w",
        "training_stress_score",
        "average_power_w",
        "maximum_power_w",
        "total_cycles_or_strokes",
        "average_swolf",
        "average_stroke_rate_per_minute",
        "steps",
        "total_repetitions",
        "total_sets",
        "body_battery_drain",
        "minimum_temperature_c",
        "decompression_required",
        "best_lap_seconds",
        "lap_count",
        "maximum_temperature_c",
        "average_respiration_brpm",
        "minimum_respiration_brpm",
        "maximum_respiration_brpm",
        "moving_time_seconds",
        "elapsed_time_seconds",
        "minimum_altitude_m",
        "maximum_altitude_m"
    ];
}
