<#
.SYNOPSIS
Adds or revises entries of the exercise catalogue from a JSON content file.

.DESCRIPTION
The catalogue has no authoring surface either: GET /api/v1/exercises is the only
endpoint (ExerciseEndpoints), and the only writers of app.exercises and
app.exercise_revisions in the repository are supabase/seed.sql and a pgTAP test.
An athlete who trains an exercise the seed never imagined cannot record it, and
a plan cannot prescribe what the catalogue does not hold.

It emits one transactional SQL script with the owner isolation the API applies
(set local role rp_api plus request.jwt.claim.sub) and, per entry:

  1. inserts the exercise when its slug is new, or updates canonical name,
     movement pattern and equipment when they changed;
  2. inserts revision 1 when the exercise has none;
  3. inserts the next revision, pointing at the previous one through
     supersedes_id, when the technique text changed -- revisions are
     append-only for rp_api, which holds insert but not update or delete.

Nothing happens when neither the exercise nor its technique changed, so the
script converges instead of piling up revisions on every run.

Images are out of scope: exercise_media rows carry a licence and a checksum, so
they stay with the seed. Until an exercise has media its card shows the initial
of its name, which is the fallback PlannedExercise already implements.

A new catalogue entry is invisible in the app until a session prescribes it --
technique now lives inside the day that asks for it, not in a section of its
own. Use scripts/Set-PlannedSessionBlocks.ps1 to prescribe it.

.EXAMPLE
pwsh ./scripts/Set-ExerciseCatalog.ps1 `
    -ContentPath ./scripts/exercise-catalog.sample.json `
    -OwnerId 11111111-1111-4111-8111-111111111111 `
    -DatabaseUrl postgresql://postgres:postgres@127.0.0.1:54322/postgres
#>
param(
    [Parameter(Mandatory = $true)]
    [string] $ContentPath,

    [Parameter(Mandatory = $true)]
    [ValidatePattern('^[0-9a-fA-F-]{36}$')]
    [string] $OwnerId,

    [string] $DatabaseUrl,

    [string] $SqlOutPath
)

$ErrorActionPreference = 'Stop'

$resolvedContent = (Resolve-Path -LiteralPath $ContentPath).Path
$content = Get-Content -LiteralPath $resolvedContent -Raw -Encoding utf8 | ConvertFrom-Json

if (-not $content.exercises -or $content.exercises.Count -eq 0) {
    throw 'The content file needs at least one exercise.'
}

$required = @('slug', 'canonicalName', 'displayName', 'briefDescription', 'setup', 'execution', 'safetyCues')
$seenSlugs = @{}
foreach ($exercise in $content.exercises) {
    foreach ($field in $required) {
        if (-not $exercise.$field) { throw "Every exercise needs a $field; '$($exercise.slug)' has none." }
    }
    # Same shape the table checks, so a bad slug fails here instead of halfway
    # through the transaction.
    if ($exercise.slug -cnotmatch '^[a-z0-9]+(?:-[a-z0-9]+)*$') {
        throw "Slug '$($exercise.slug)' is not lowercase words joined by single hyphens."
    }
    if ($seenSlugs.ContainsKey($exercise.slug)) { throw "Slug '$($exercise.slug)' appears twice in the file." }
    $seenSlugs[$exercise.slug] = $true

    # Ids come from the caller, as the API does in C#; the inserts below only
    # use them when the slug or the technique turns out to be new.
    $exercise | Add-Member -NotePropertyName 'newExerciseId' -NotePropertyValue ([Guid]::NewGuid().ToString()) -Force
    $exercise | Add-Member -NotePropertyName 'newRevisionId' -NotePropertyValue ([Guid]::NewGuid().ToString()) -Force
}

# The payload travels as a dollar-quoted jsonb literal, so the only sequence
# that could break out of it is the closing tag itself.
$payload = $content | ConvertTo-Json -Depth 12 -Compress
if ($payload.Contains('$rp_catalog$')) { throw 'The content file cannot contain the string $rp_catalog$.' }

$sql = @"
-- Generated by scripts/Set-ExerciseCatalog.ps1 from $([IO.Path]::GetFileName($resolvedContent)).
-- Owner isolation mirrors OwnerTransactionContext: role rp_api plus the jwt claim.
begin;

set local role rp_api;
select
  set_config('request.jwt.claim.sub', '$OwnerId', true),
  set_config('request.jwt.claim.role', 'authenticated', true),
  set_config(
    'request.jwt.claims',
    jsonb_build_object('sub', '$OwnerId', 'role', 'authenticated')::text,
    true);

do `$rp`$
declare
  owner_id_value uuid := app.current_owner_id();
  content jsonb := `$rp_catalog`$$payload`$rp_catalog`$::jsonb;
  entry jsonb;
  exercise_row app.exercises%rowtype;
  revision_row app.exercise_revisions%rowtype;
  exercise_id_value uuid;
begin
  if owner_id_value is null then
    raise exception 'Owner context is missing: request.jwt.claim.sub is not set.';
  end if;

  for entry in select * from jsonb_array_elements(content->'exercises') loop
    select * into exercise_row
    from app.exercises
    where owner_id = owner_id_value and slug = entry->>'slug';

    if not found then
      insert into app.exercises (
        id, owner_id, slug, canonical_name, movement_pattern, equipment)
      values (
        (entry->>'newExerciseId')::uuid, owner_id_value, entry->>'slug',
        entry->>'canonicalName', entry->>'movementPattern', entry->>'equipment');
      exercise_id_value := (entry->>'newExerciseId')::uuid;
      raise notice 'Exercise % added.', entry->>'slug';
    else
      exercise_id_value := exercise_row.id;
      if exercise_row.canonical_name is distinct from entry->>'canonicalName'
        or exercise_row.movement_pattern is distinct from entry->>'movementPattern'
        or exercise_row.equipment is distinct from entry->>'equipment' then
        update app.exercises
        set canonical_name = entry->>'canonicalName',
            movement_pattern = entry->>'movementPattern',
            equipment = entry->>'equipment',
            updated_at = now()
        where owner_id = owner_id_value and id = exercise_id_value;
        raise notice 'Exercise % updated.', entry->>'slug';
      end if;
    end if;

    select * into revision_row
    from app.exercise_revisions
    where owner_id = owner_id_value and exercise_id = exercise_id_value
    order by version_number desc
    limit 1;

    if found
      and revision_row.display_name = entry->>'displayName'
      and revision_row.brief_description = entry->>'briefDescription'
      and revision_row.setup = entry->>'setup'
      and revision_row.execution = entry->>'execution'
      and revision_row.safety_cues = entry->>'safetyCues' then
      raise notice 'Exercise % keeps revision v%.', entry->>'slug', revision_row.version_number;
      continue;
    end if;

    -- A revision is never rewritten: plans already prescribe the previous one,
    -- and their content has to keep saying what it said when it was published.
    insert into app.exercise_revisions (
      id, owner_id, exercise_id, version_number, display_name,
      brief_description, setup, execution, safety_cues, supersedes_id)
    values (
      (entry->>'newRevisionId')::uuid, owner_id_value, exercise_id_value,
      coalesce(revision_row.version_number, 0) + 1,
      entry->>'displayName', entry->>'briefDescription', entry->>'setup',
      entry->>'execution', entry->>'safetyCues', revision_row.id);
    raise notice 'Exercise % now at revision v%.',
      entry->>'slug', coalesce(revision_row.version_number, 0) + 1;
  end loop;
end
`$rp`$;

commit;
"@

if ($SqlOutPath) {
    $sql | Set-Content -LiteralPath $SqlOutPath -Encoding utf8 -NoNewline
}

if (-not $DatabaseUrl) {
    if (-not $SqlOutPath) { $sql }
    return
}

$psql = Get-Command psql -ErrorAction SilentlyContinue
if ($null -eq $psql) {
    throw 'psql is required to apply the script; rerun without -DatabaseUrl and paste the SQL into the Supabase SQL editor.'
}

$scriptPath = Join-Path ([IO.Path]::GetTempPath()) "exercise-catalog-$([Guid]::NewGuid()).sql"
# psql reads the file with the client encoding, which on Windows comes from the
# console code page, not from the file. The technique text is Spanish prose the
# athlete reads inside the session, so an unset encoding stores mojibake.
$previousClientEncoding = $env:PGCLIENTENCODING
$env:PGCLIENTENCODING = 'UTF8'
try {
    $sql | Set-Content -LiteralPath $scriptPath -Encoding utf8 -NoNewline
    & $psql.Source @('--set', 'ON_ERROR_STOP=1', '--no-psqlrc', '--file', $scriptPath, $DatabaseUrl)
    if ($LASTEXITCODE -ne 0) { throw "psql exited with code $LASTEXITCODE; nothing was committed." }
}
finally {
    $env:PGCLIENTENCODING = $previousClientEncoding
    Remove-Item -LiteralPath $scriptPath -ErrorAction SilentlyContinue
}
